In [1]:
import numpy as np
import cv2
import os
from utils import window_base_matching_cosine,window_based_l1,window_based_l2,pixel_based_l1,pixel_based_l2

In [2]:
os.chdir('/Users/microwave/AIO_2024/Module_2/Image_depth_estimation/data/Tsukuba')
left_img_path = 'left.png'
right_img_path = 'right.png'
disparity_range = 16
pixel_based_l1(left_img_path,right_img_path,disparity_range,save_result=True)
pixel_based_l2(left_img_path,right_img_path,disparity_range,save_result=True)

Saving result...
Done
Saving result...
Done


array([[ 0,  0,  0, ...,  0,  0,  0],
       [ 0,  0,  0, ...,  0,  0,  0],
       [ 0,  0,  0, ...,  0,  0,  0],
       ...,
       [ 0,  0,  0, ...,  0, 16,  0],
       [ 0,  0,  0, ..., 16, 32,  0],
       [ 0,  0,  0, ..., 64, 64,  0]], dtype=uint8)

In [3]:
os.chdir('/Users/microwave/AIO_2024/Module_2/Image_depth_estimation/data/Aloe')
left_img_path = 'Aloe_left_1.png'
right_img_path = 'Aloe_right_1.png'
DISPARITY_RANGE = 64
KERNEL_SIZE = 3
window_based_l1(left_img_path,right_img_path,DISPARITY_RANGE,'Aloe_disparity_l1_window',KERNEL_SIZE)
window_based_l2(left_img_path,right_img_path,DISPARITY_RANGE,'Aloe_disparity_l2_window',KERNEL_SIZE)

Done
Saving result
Done


array([[  0,   0,   0, ...,   0,   0,   0],
       [  0,   0,   3, ...,  45,  48,  48],
       [  0,   0,   3, ...,  45,  48,  51],
       ...,
       [  0,   0,   0, ..., 102,  72,  72],
       [  0,   0,   0, ...,  66,  69, 132],
       [  0,   0,   3, ..., 129, 129, 129]], dtype=uint8)

In [4]:
left_img_path = 'Aloe_left_1.png'
right_img_path = 'Aloe_right_2.png'
right_img_path_1 = 'Aloe_right_3.png'
DISPARITY_RANGE = 64
KERNEL_SIZE = 5
window_based_l1(left_img_path,right_img_path,DISPARITY_RANGE,'Aloe_right_2_disparity_l1',KERNEL_SIZE)
window_based_l1(left_img_path,right_img_path_1,DISPARITY_RANGE,'Aloe_right_3_disparity_l1',KERNEL_SIZE)

Done
Done


array([[  0,   0,   0, ...,   0,   0,   0],
       [  0,   0,   0, ...,   0,   0,   0],
       [  0,   0,   0, ...,  45, 168,   0],
       ...,
       [  0,   0,   0, ..., 141, 144,   0],
       [  0,   0,   0, ..., 141, 126,   0],
       [  0,   0,   0, ...,   0,   0,   0]], dtype=uint8)

The problem with the different disparity depth when comparing Aloe_left_1 with Aloe_right_2 images is the contrast in 2 images. 

Two images took at same angle and viewpoint but the author personally changed it contrast. 

When applying to the disparity calculation, the different between pixels make the computation harder. To further clarify, the constrast of an image is linearity dependance while L1 and L2 invariant to linear changes.

In [5]:
left_img_path = 'Aloe_left_1.png'
right_img_path = 'Aloe_right_2.png'
right_img_path_1 = 'Aloe_right_3.png'
DISPARITY_RANGE = 64
KERNEL_SIZE = 5
window_base_matching_cosine(left_img_path,right_img_path,DISPARITY_RANGE,'Aloe_right_2_cosine',KERNEL_SIZE)
window_base_matching_cosine(left_img_path,right_img_path_1,DISPARITY_RANGE,'Aloe_right_3_cosine',KERNEL_SIZE)

Done
Done


array([[  0,   0,   0, ...,   0,   0,   0],
       [  0,   0,   0, ...,   0,   0,   0],
       [  0,   0,   0, ...,  48,   0,   0],
       ...,
       [  0,   0,   0, ..., 126,   0,   0],
       [  0,   0,   0, ...,   0,   0,   0],
       [  0,   0,   0, ...,   0,   0,   0]], dtype=uint8)