In [4]:
import torch
import torch.nn as nn
from torch_softmax import MySoftmaxStable, MySoftmaxt
from ward_oop import Student, Teacher, Doctor, Ward
from my_stack import MyStack
from my_queue import Myqueue

### Exercise 1 

In [5]:
data = torch.Tensor([1,2,3])
softmax_function = nn.Softmax(dim = 0)
output = softmax_function(data)
output

tensor([0.0900, 0.2447, 0.6652])

### Exercise 2

In [6]:
data = torch.Tensor([5,2,4])
my_softmax = MySoftmaxt() 
output = my_softmax(data)
output

tensor([0.7054, 0.0351, 0.2595])

### Exercise 3

In [7]:

data = torch.Tensor([1,2,300000000])
my_softmax = MySoftmaxt() # type: ignore
output = my_softmax(data)
output

tensor([0., 0., nan])

### Excercise 4

In [8]:
data = torch.Tensor([1,2,3])
my_softmax = MySoftmaxStable() # type: ignore
output = my_softmax(data)
output

tensor([0.0900, 0.2447, 0.6652])

### Exercise 5

In [9]:
student1 = Student('studentZ2023',2011,'6')
student1.describe()

Student - Name: studentZ2023 - YoB: 2011 - Grade: 6


### Exercise 6

In [10]:
teacher1 = Teacher('teacherZ2023',1991,'History')
teacher1.describe()

Teacher - Name: teacherZ2023 - YoB: 1991 - Subject: History


### Exercise 7

In [11]:
doctor1 = Doctor('doctorZ2023',1981,'Endocrinologists')
doctor1.describe()

Doctor - Name: doctorZ2023 - YoB: 1981 - Specialist: Endocrinologists


### Exercise 8

In [12]:
student1 = Student('studentA',2010,'7')
teacher1 = Teacher('teacherA',1969,'Math')
teacher2 = Teacher('teacherB',1995,'History')
doctor1 = Doctor('doctorA',1945,'Endocrinologists')
doctor2 = Doctor('docterB',1975,'Cardiologists')
ward1 = Ward('Ward1')
ward1.add_person(student1)
ward1.add_person(teacher1)
ward1.add_person(teacher2)
ward1.add_person(doctor1)
ward1.add_person(doctor2)
ward1.count_doctor()

2

### Exercise 9

In [13]:
stack1 = MyStack(5)
stack1.push(1)
stack1.push(2)
print(stack1.is_full())

False


### Exercise 10

In [14]:
stack1 = MyStack(5)
stack1.push(1)
stack1.push(2)
print(stack1.top())

2


### Exercise 11

In [15]:
queue1 = Myqueue(5)
queue1.enqueue(1)
queue1.enqueue(2)
print(queue1.is_full())

False


### Excercise 12

In [16]:
queue1 = Myqueue(5)
queue1.enqueue(1)
queue1.enqueue(2)
print(queue1.front())

1
