In [1]:
%pip install gdown
%pip install matplotlib
!gdown 1i9dqan21DjQoG5Q_VEvm0LrVwAlXD0vB
!gdown 1iA0WmVfW88HyJvTBSQDI5vesf-pgKabq


[notice] A new release of pip available: 22.3.1 -> 24.1.2
[notice] To update, run: pip3 install --upgrade pip
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip available: 22.3.1 -> 24.1.2
[notice] To update, run: pip3 install --upgrade pip
Note: you may need to restart the kernel to use updated packages.
Downloading...
From: https://drive.google.com/uc?id=1i9dqan21DjQoG5Q_VEvm0LrVwAlXD0vB
To: /Users/microwave/AIO_2024/Week1/dog.jpeg
100%|██████████████████████████████████████| 33.7k/33.7k [00:00<00:00, 3.12MB/s]
Downloading...
From: https://drive.google.com/uc?id=1iA0WmVfW88HyJvTBSQDI5vesf-pgKabq
To: /Users/microwave/AIO_2024/Week1/advertising.csv
100%|██████████████████████████████████████| 4.06k/4.06k [00:00<00:00, 8.62MB/s]


In [1]:
import numpy as np
import matplotlib.image as mpimg
import pandas as pd
import os
import warnings

new_path = '/Users/microwave/AIO_2024/Week1'
os.chdir(new_path)

/var/folders/nk/6_ymhlt94l97ghl62d13wtym0000gn/T/ipykernel_10105/124952039.py:3: DeprecationWarning: 
Pyarrow will become a required dependency of pandas in the next major release of pandas (pandas 3.0),
(to allow more performant data types, such as the Arrow string type, and better interoperability with other libraries)
but was not found to be installed on your system.
If this would cause problems for you,
please provide us feedback at https://github.com/pandas-dev/pandas/issues/54466
        
  import pandas as pd


FileNotFoundError: [Errno 2] No such file or directory: '/Users/microwave/AIO_2024/Week1'

### Exercise 1

In [3]:
arr = np.arange(0,10,1)
print(arr)

[0 1 2 3 4 5 6 7 8 9]


### Exercise 2

In [3]:
arr = np.ones((3,3), dtype=bool)
print(arr)

[[ True  True  True]
 [ True  True  True]
 [ True  True  True]]


### Exercise 3

In [5]:
arr = np.arange(0,10)
print(arr[arr % 2 == 1])

[1 3 5 7 9]


### Exercise 4

In [29]:
arr = np.arange(0,10)
arr[arr % 2 == 1] = -1
print(arr)

[ 0 -1  2 -1  4 -1  6 -1  8 -1]


### Exercise 5

In [6]:
arr = np.arange(10)
arr_2d = arr.reshape(2,-1) # let np automatic chosse appropriate rows
print(arr_2d)

[[0 1 2 3 4]
 [5 6 7 8 9]]


### Exercise 6

In [7]:
arr1 = np.arange(10).reshape(2,-1)
arr2 = np.repeat(1,10).reshape(2,-1)
c = np.concatenate([arr1,arr2],axis = 0) #axis = 0 -> by col
print(c)

[[0 1 2 3 4]
 [5 6 7 8 9]
 [1 1 1 1 1]
 [1 1 1 1 1]]


### Exercise 7

In [8]:
arr1 = np.arange(10).reshape(2,-1)
arr2 = np.repeat(1,10).reshape(2,-1)
c = np.concatenate([arr1,arr2],axis = 1)
print(c)

[[0 1 2 3 4 1 1 1 1 1]
 [5 6 7 8 9 1 1 1 1 1]]


### Exercise 8

In [9]:
arr = np.array([1,2,3])
print(np.repeat(arr,3))
print(np.tile(arr,3))

[1 1 1 2 2 2 3 3 3]
[1 2 3 1 2 3 1 2 3]


### Exercise 9

In [10]:
a = np.array([2,6,1,9,10,3,27])
index = np.where((a >= 5) & (a <= 10))
print(a[index])

[ 6  9 10]


### Exercise 10

In [11]:
def maxx(x,y):
    if x >= y:
        return x
    else:
        return y
    
a = np.array([5,7,9,8,6,4,5])
b = np.array([6,3,4,8,9,7,1])
pair_max = np.vectorize(maxx,otypes=[float])
print(pair_max(a,b))

[6. 7. 9. 8. 9. 7. 5.]


### Exercise 11

In [12]:
a = np.array([5,7,9,8,6,4,5])
b = np.array([6,3,4,8,9,7,1])

print(np.where(a < b,b,a))

[6 7 9 8 9 7 5]


### Exercises 12 & 13 & 14

In [13]:

img = mpimg.imread('dog.jpeg')
import matplotlib.pyplot as plt

# Retrieve the color channel of the image
red_chanel = img[0,0,0]  #height, width, color 
green_chanel = img[0,0,1]  #height, width, color 
blue_chanel = img[0,0,2]  #height, width, color 

lightness = (np.max([red_chanel,blue_chanel,green_chanel]) + np.min([red_chanel,blue_chanel,green_chanel])) / 2
average = (red_chanel + blue_chanel + green_chanel) / 3
luminousity = 0.21 * red_chanel + 0.72 * green_chanel + 0.07 * blue_chanel

gray_img_01 = np.zeros((img.shape[0], img.shape[1])) 
gray_img_01[0, 0] = lightness
gray_img_02 = np.zeros((img.shape[0], img.shape[1])) 
gray_img_02[0, 0] = average
gray_img_03 = np.zeros((img.shape[0], img.shape[1])) 
gray_img_03[0, 0] = luminousity

print(gray_img_01[0,0])
print(gray_img_02[0,0])
print(gray_img_03[0,0])

102.5
22.333333333333332
126.22999999999999


/var/folders/nk/6_ymhlt94l97ghl62d13wtym0000gn/T/ipykernel_4462/316667315.py:10: RuntimeWarning: overflow encountered in scalar add
  average = (red_chanel + blue_chanel + green_chanel) / 3


### Exercises 15 to 21

In [14]:
df = pd.read_csv('advertising.csv')
data = df.to_numpy()

In [15]:
df.describe()

TV       Radio   Newspaper       Sales
count  200.000000  200.000000  200.000000  200.000000
mean   147.042500   23.264000   30.554000   15.130500
std     85.854236   14.846809   21.778621    5.283892
min      0.700000    0.000000    0.300000    1.600000
25%     74.375000    9.975000   12.750000   11.000000
50%    149.750000   22.900000   25.750000   16.000000
75%    218.825000   36.525000   45.100000   19.050000
max    296.400000   49.600000  114.000000   27.000000

In [16]:
max_sale = np.max(data[:,3])
index_max_sale = np.where(data[:,3] == max_sale)[0]
print(max_sale)
print(index_max_sale)

27.0
[175]


In [17]:
print(np.mean(data[:,0]))

147.0425


In [18]:
mask = data[:,3] >= 20
print(np.sum(mask))

np.count_nonzero(np.where(data[:, 3] >= 20)[0]) 

40


39

In [19]:
mask = data[:, 3] >= 15
filtered_radio = data[:, 1][mask]
avg_radio = np.mean(filtered_radio)
print(avg_radio)

26.22293577981651


In [20]:
newspaper_mean = np.mean(data[:,2])
condition = data[:,2] > newspaper_mean
filtered_sale = data[:,3][condition]
np.sum(filtered_sale)


1405.1

In [33]:
mean_sale = np.mean(data[:,3])
sale = data[:,3]
score = np.where(sale > mean_sale,'Good',np.where(sale == mean_sale,'Average','Bad'))
score[7:10]


array(['Bad', 'Bad', 'Good'], dtype='<U7')

In [32]:
closest_mask = np.argmin(np.abs(sale - mean_sale))
A = sale[closest_mask]
score = np.where(sale > A,'Good',np.where(sale == A,'Average','Bad'))
score[7:10]

array(['Bad', 'Bad', 'Good'], dtype='<U7')